-- lvim.builtin.lualine.on_config_done = function(lualine)
--   local config = lualine.get_config()
--   table.insert(config.sections.lualine_y, require("xbase.statusline").lualine())
--   lualine.setup(config)
-- end
